# Generated by Django 4.2.6 on 2023-11-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_project_url_project_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=models.ManyToManyField(blank=True, to='resume.techstack'),
        ),
    ]
