# Generated by Django 4.2.6 on 2023-11-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_delete_education_resume_cv_resume_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='cv',
        ),
        migrations.AddField(
            model_name='resume',
            name='cv_url',
            field=models.URLField(blank=True),
        ),
    ]
